-- VS Code's built-in Default High Contrast (theme-defaults/themes/hc_black.json).
-- UI borders and selections are adapted for Neovim's terminal interface.
vim.opt.background = "dark"
vim.opt.termguicolors = true
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
	vim.cmd("syntax reset")
end
vim.g.colors_name = "vscode_hc"

local c = {
	bg = "#000000",
	fg = "#FFFFFF",
	muted = "#A0A0A0",
	whitespace = "#7C7C7C",
	line = "#101010",
	border = "#6FC3DF",
	blue = "#569CD6",
	variable = "#9CDCFE",
	comment = "#7CA668",
	string = "#CE9178",
	number = "#B5CEA8",
	func = "#DCDCAA",
	type = "#4EC9B0",
	control = "#C586C0",
	operator = "#D4D4D4",
	regex = "#D16969",
	error = "#F44747",
	warn = "#F9F1A5",
	selection = "#008000",
}

local groups = {
	Normal = { fg = c.fg, bg = c.bg },
	NormalNC = { fg = c.fg, bg = c.bg },
	NormalFloat = { fg = c.fg, bg = c.bg },
	FloatBorder = { fg = c.border, bg = c.bg },
	FloatTitle = { fg = c.fg, bg = c.bg, bold = true },
	WinSeparator = { fg = c.border, bg = c.bg },
	SignColumn = { fg = c.fg, bg = c.bg },
	FoldColumn = { fg = c.muted, bg = c.bg },
	Folded = { fg = c.muted, bg = c.line },
	LineNr = { fg = c.muted, bg = c.bg },
	CursorLineNr = { fg = c.fg, bg = c.line, bold = true },
	CursorLine = { bg = c.line },
	CursorColumn = { bg = c.line },
	ColorColumn = { bg = c.line },
	Cursor = { fg = c.bg, bg = c.fg },
	TermCursor = { fg = c.bg, bg = c.fg },
	Visual = { fg = c.bg, bg = c.fg },
	VisualNOS = { fg = c.bg, bg = c.fg },
	Search = { fg = c.bg, bg = c.warn },
	IncSearch = { fg = c.bg, bg = c.border, bold = true },
	CurSearch = { fg = c.bg, bg = c.border, bold = true },
	MatchParen = { fg = c.bg, bg = c.border, bold = true },
	NonText = { fg = c.whitespace },
	Whitespace = { fg = c.whitespace },
	SpecialKey = { fg = c.whitespace },
	EndOfBuffer = { fg = c.bg },
	Pmenu = { fg = c.fg, bg = c.bg },
	PmenuSel = { fg = c.fg, bg = c.selection, bold = true },
	PmenuSbar = { bg = c.line },
	PmenuThumb = { bg = c.muted },
	StatusLine = { fg = c.fg, bg = c.bg },
	StatusLineNC = { fg = c.muted, bg = c.bg },
	TabLine = { fg = c.muted, bg = c.bg },
	TabLineFill = { bg = c.bg },
	TabLineSel = { fg = c.fg, bg = c.bg, bold = true, underline = true, sp = c.border },
	WinBar = { fg = c.fg, bg = c.bg },
	WinBarNC = { fg = c.muted, bg = c.bg },
	Directory = { fg = c.border },
	Title = { fg = c.blue, bold = true },
	MoreMsg = { fg = c.number },
	Question = { fg = c.border },
	ErrorMsg = { fg = c.error },
	WarningMsg = { fg = c.warn },
	Conceal = { fg = c.muted },
	Comment = { fg = c.comment },
	Constant = { fg = c.blue },
	String = { fg = c.string },
	Character = { fg = c.blue },
	Number = { fg = c.number },
	Boolean = { fg = c.blue },
	Float = { fg = c.number },
	Identifier = { fg = c.variable },
	Function = { fg = c.func },
	Statement = { fg = c.control },
	Conditional = { fg = c.control },
	Repeat = { fg = c.control },
	Label = { fg = c.control },
	Operator = { fg = c.operator },
	Keyword = { fg = c.blue },
	Exception = { fg = c.control },
	PreProc = { fg = c.blue },
	Type = { fg = c.type },
	StorageClass = { fg = c.blue },
	Structure = { fg = c.blue },
	Typedef = { fg = c.type },
	Special = { fg = c.blue },
	SpecialChar = { fg = c.blue },
	Delimiter = { fg = c.fg },
	Underlined = { fg = c.border, underline = true },
	Ignore = { fg = c.muted },
	Error = { fg = c.error, underline = true },
	Todo = { fg = c.bg, bg = c.warn, bold = true },
	Added = { fg = c.number },
	Changed = { fg = c.blue },
	Removed = { fg = c.string },
	DiffAdd = { bg = "#003300" },
	DiffChange = { bg = "#002B45" },
	DiffDelete = { fg = c.string, bg = "#440000" },
	DiffText = { bg = "#004B70", bold = true },
	SpellBad = { sp = c.error, undercurl = true },
	SpellCap = { sp = c.blue, undercurl = true },
	SpellLocal = { sp = c.border, undercurl = true },
	SpellRare = { sp = c.control, undercurl = true },
	["@string.regexp"] = { fg = c.regex },
	["@tag"] = { fg = c.blue },
	["@tag.delimiter"] = { fg = "#808080" },
	["@markup.heading"] = { fg = "#6796E6", bold = true },
	["@markup.strong"] = { bold = true },
	["@markup.italic"] = { italic = true },
	["@markup.strikethrough"] = { strikethrough = true },
}

local links = {
	["@variable"] = "Identifier",
	["@variable.builtin"] = "Keyword",
	["@variable.parameter"] = "Identifier",
	["@variable.member"] = "Identifier",
	["@property"] = "Identifier",
	["@constant"] = "Constant",
	["@constant.builtin"] = "Constant",
	["@module"] = "Type",
	["@type"] = "Type",
	["@type.builtin"] = "Keyword",
	["@constructor"] = "Type",
	["@function"] = "Function",
	["@function.builtin"] = "Function",
	["@function.macro"] = "Function",
	["@keyword"] = "Keyword",
	["@keyword.conditional"] = "Conditional",
	["@keyword.repeat"] = "Repeat",
	["@keyword.return"] = "Statement",
	["@keyword.exception"] = "Exception",
	["@keyword.import"] = "Statement",
	["@keyword.directive"] = "PreProc",
	["@operator"] = "Operator",
	["@punctuation"] = "Delimiter",
	["@punctuation.special"] = "Special",
	["@tag.attribute"] = "Identifier",
	["@markup.raw"] = "String",
	["@markup.link"] = "Underlined",
	["@markup.link.url"] = "Underlined",
	["@lsp.type.class"] = "Type",
	["@lsp.type.enum"] = "Type",
	["@lsp.type.interface"] = "Type",
	["@lsp.type.struct"] = "Type",
	["@lsp.type.type"] = "Type",
	["@lsp.type.typeParameter"] = "Type",
	["@lsp.type.namespace"] = "Type",
	["@lsp.type.function"] = "Function",
	["@lsp.type.method"] = "Function",
	["@lsp.type.variable"] = "Identifier",
	["@lsp.type.parameter"] = "Identifier",
	["@lsp.type.property"] = "Identifier",
	["@lsp.type.enumMember"] = "Constant",
	GitSignsAdd = "Added",
	GitSignsChange = "Changed",
	GitSignsDelete = "Removed",
	NeoTreeNormal = "Normal",
	NeoTreeNormalNC = "NormalNC",
	NeoTreeEndOfBuffer = "EndOfBuffer",
	NeoTreeWinSeparator = "WinSeparator",
	NeoTreeDirectoryName = "Directory",
	NeoTreeDirectoryIcon = "Directory",
	NeoTreeRootName = "Title",
	NeoTreeCursorLine = "PmenuSel",
	TelescopeNormal = "NormalFloat",
	TelescopeBorder = "FloatBorder",
	TelescopeSelection = "PmenuSel",
	TelescopeMatching = "Special",
	BlinkCmpMenu = "Pmenu",
	BlinkCmpMenuBorder = "FloatBorder",
	BlinkCmpMenuSelection = "PmenuSel",
	BlinkCmpDoc = "NormalFloat",
	BlinkCmpDocBorder = "FloatBorder",
}

for group, color in pairs({ Error = c.error, Warn = c.warn, Info = c.border, Hint = c.type, Ok = c.number }) do
	groups["Diagnostic" .. group] = { fg = color }
	groups["DiagnosticVirtualText" .. group] = { fg = color, bg = c.bg }
	groups["DiagnosticUnderline" .. group] = { sp = color, undercurl = true }
end

for name, opts in pairs(groups) do
	vim.api.nvim_set_hl(0, name, opts)
end
for name, target in pairs(links) do
	vim.api.nvim_set_hl(0, name, { link = target })
end

local terminal = {
	"#000000", "#CD3131", "#0DBC79", "#E5E510", "#2472C8", "#BC3FBC", "#11A8CD", "#E5E5E5",
	"#666666", "#F14C4C", "#23D18B", "#F5F543", "#3B8EEA", "#D670D6", "#29B8DB", "#FFFFFF",
}
for index, color in ipairs(terminal) do
	vim.g["terminal_color_" .. (index - 1)] = color
end
